# Name of this workflow file
name: Build and Push to GCP

# Trigger this workflow only after 'rust_compile_tests' completes
on:
  workflow_run:
    workflows: ["rust_compile_tests"]
    types:
      - completed
  push:
    branches: [ "**" ]  # Trigger on pushes to any branch

jobs:
  build-and-push:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if rust_compile_tests succeeded
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}  # Secret must contain the bucket name
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}  # Secret must contain GCP service account key JSON

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'  # Secret must contain GCP service account key JSON

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      # TODO -> make variable for flavours

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg BUCKET_NAME=$BUCKET_NAME \
            --build-arg GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
            -t us-central1-docker.pkg.dev/sentinela-diagnosis-dev/sentinela-diagnosis-dev-docker-repo/exam_gateway:latest .

          docker push us-central1-docker.pkg.dev/sentinela-diagnosis-dev/sentinela-diagnosis-dev-docker-repo/exam_gateway:latest
      # TODO -> make variable for flavours.